#!/usr/bin/env php
<?php
declare(strict_types=1);

use Elephox\Console\ConsoleApplicationBuilder;

require_once 'vendor/autoload.php';
const APP_ROOT = __DIR__;

$builder = ConsoleApplicationBuilder::create()
	->addLogging()
	->addWhoops()
;

$builder->commands->loadFromNamespace("Elephox\\Development\\Commands");

$app = $builder->build();
try {
	$app->run();
} catch (Throwable $e) {
	$app->exceptionHandler()->handleException($e);
}
