#!/usr/bin/env php
<?php
declare(strict_types=1);

use Elephox\Builder\Whoops\AddsWhoopsHandler;
use Elephox\Console\ConsoleApplicationBuilder;
use Elephox\Console\DefaultExceptionHandler;
use Elephox\Support\Contract\ErrorHandler;
use Elephox\Web\Commands\ServeCommand;

require_once 'bootstrap.php';

/**
 * @internal
 */
class ConsoleAppBuilder extends ConsoleApplicationBuilder {
	use AddsWhoopsHandler;
}

$builder = ConsoleAppBuilder::create();
$builder->addLogging();
$builder->addWhoops();
$builder->services->addSingleton(ErrorHandler::class, DefaultExceptionHandler::class);

$builder->commands->loadFromNamespace("Elephox\\Development\\Commands");
$builder->commands->loadFromClass(ServeCommand::class);

$app = $builder->build();
$app->run();
