<?php
declare(strict_types=1);

namespace Elephox\Http\PSR7;

use Elephox\Files\Directory;
use Elephox\Files\File;
use Elephox\Http\UploadedFile;
use Http\Psr7Test\UploadedFileIntegrationTest;

/**
 * @covers \Elephox\Http\UploadedFile
 * @covers \Elephox\Files\AbstractFilesystemNode
 * @covers \Elephox\Files\Directory
 * @covers \Elephox\Files\File
 * @covers \Elephox\Files\Path
 * @covers \Elephox\Stream\ResourceStream
 * @covers \Elephox\Stream\StringStream
 * @covers \Elephox\Files\FileException
 * @covers \Elephox\Files\FileNotFoundException
 * @covers \Elephox\Files\FilesystemNodeNotFoundException
 * @covers \Elephox\Files\UnreadableFileException
 *
 * @internal
 */
class UploadedFileTest extends UploadedFileIntegrationTest
{
	public static function tearDownAfterClass(): void
	{
		parent::tearDownAfterClass(); // TODO: Change the autogenerated stub

		Directory::from('.tmp')->delete();
	}

	public function createSubject(): UploadedFile
	{
		$file = File::temp('.tmp');
		$file->writeContents('Foo Bar');

		return new UploadedFile('filename.txt', 'C:\\Users\\Foo\\Downloads', $file);
	}
}
