name: Cache Pipeline
on:
  push:
    paths:
      - '.github/workflows/cache.yml'
      - '.github/workflows/splitsh.yml'
      - 'modules/Cache/**'

jobs:
  splitsh:
    if: ${{ github.ref_type == 'branch' }}
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@develop
    with:
      repo: 'elephox-dev/cache'
      dir: 'modules/Cache/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_CACHE_KEY }}
