name: Collection Pipeline
on:
  push:
    paths:
      - '.github/workflows/collection.yml'
      - '.github/workflows/splitsh.yml'
      - 'modules/Collection/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@develop
    with:
      repo: 'elephox-dev/collection'
      dir: 'modules/Collection/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_COLLECTION_KEY }}
