name: Collection Pipeline
on:
  push:
    branches:
      - main
    paths:
      - 'composer.json'
      - 'composer.lock'
      - 'modules/Collection/**'
      - '.github/workflows/collection.yml'
      - '.github/workflows/splitsh.yml'
      - '.github/workflows/unit-tests.yml'

jobs:
  unit-tests-ubuntu-latest-php-8-1:
    uses: philly-framework/base/.github/workflows/unit-tests.yml@main
    with:
      os: 'ubuntu-latest'
      php-version: '8.1'
      testsuite: 'Collection'

  changes:
    runs-on: ubuntu-latest
    outputs:
      root: ${{ steps.changes.outputs.root }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            root:
              - modules/Collection/

  splitsh:
    needs: changes
    if: ${{ needs.changes.outputs.root == 'true' }}
    uses: philly-framework/base/.github/workflows/splitsh.yml@main
    with:
      repo: 'philly-framework/collection'
      dir: 'modules/Collection/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_COLLECTION_KEY }}
