name: Collection Pipeline
on:
  push:
    branches:
      - main
    paths:
      - 'composer.lock'
      - 'modules/Collection/**'
      - '.github/workflows/collection.yml'
      - '.github/workflows/splitsh.yml'
      - '.github/workflows/unit-tests.yml'

jobs:
  unit-tests-ubuntu-latest-php-8-1:
    uses: philly-framework/base/.github/workflows/unit-tests.yml@main
    with:
      os: 'ubuntu-latest'
      php-version: '8.1'
      testsuite: 'Collection'

  unit-tests-ubuntu-latest-php-8-2:
    uses: philly-framework/base/.github/workflows/unit-tests.yml@main
    with:
      os: 'ubuntu-latest'
      php-version: '8.2'
      testsuite: 'Collection'

  splitsh:
    uses: philly-framework/base/.github/workflows/splitsh.yml@main
    with:
      repo: 'philly-framework/collection'
      dir: 'modules/Collection/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_COLLECTION_KEY }}
