name: Console Pipeline
on:
  push:
    paths:
      - '.github/workflows/console.yml'
      - '.github/workflows/splitsh.yml'
      - 'modules/Console/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@main
    with:
      repo: 'elephox-dev/console'
      dir: 'modules/Console/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_CONSOLE_KEY }}
