name: DI Pipeline
on:
  push:
    paths:
      - '.github/workflows/di.yml'
      - '.github/workflows/splitsh.yml'
      - 'modules/DI/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@main
    with:
      repo: 'elephox-dev/di'
      dir: 'modules/DI/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_DI_KEY }}
