name: Events Pipeline
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/events.yml'
      - 'modules/Events/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@main
    with:
      repo: 'elephox-dev/events'
      dir: 'modules/Events/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_EVENTS_KEY }}
