name: Files Pipeline
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/files.yml'
      - 'modules/Http/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@main
    with:
      repo: 'elephox-dev/files'
      dir: 'modules/Files/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_FILES_KEY }}
