name: Http Pipeline
on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/http.yml'
      - '.github/workflows/splitsh.yml'
      - 'modules/Http/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@main
    with:
      repo: 'elephox-dev/http'
      dir: 'modules/Http/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_HTTP_KEY }}
