name: Logging Pipeline
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/logging.yml'
      - 'modules/Logging/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@main
    with:
      repo: 'elephox-dev/logging'
      dir: 'modules/Logging/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_LOGGING_KEY }}
