name: Deploy to Collection repository
on:
  push:
    branches:
      - main
    paths:
      - 'src/Collection/**'
      - '.github/workflows/splitsh-collection.yml'

jobs:
  Split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: philly-framework/action-splitsh@master
        with:
          split: 'philly-framework/collection'
          split_deploy_key: ${{ secrets.SPLITSH_COLLECTION_KEY }}
          split_prefix: 'src/Collection/'
          split_branch: main
