name: Support Pipeline
on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/support.yml'
      - '.github/workflows/splitsh.yml'
      - 'modules/Support/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: elephox-dev/framework/.github/workflows/splitsh.yml@main
    with:
      repo: 'elephox-dev/support'
      dir: 'modules/Support/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_SUPPORT_KEY }}
