name: Support Pipeline
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/support.yml'
      - 'modules/Support/**'

jobs:
  splitsh:
    name: ⏩ Update Module Repository
    uses: philly-framework/base/.github/workflows/splitsh.yml@main
    with:
      repo: 'philly-framework/support'
      dir: 'modules/Support/'
    secrets:
      deploy_key: ${{ secrets.SPLITSH_SUPPORT_KEY }}
