name: Tests

on:
  push:
    paths:
      - src/
      - test/
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  composer-script:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        script: ['unit-test', 'mutation-test', 'static-analysis']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - run: composer install --prefer-dist --no-progress --no-interaction --no-suggest --no-scripts --no-ansi
      - run: composer run-script ${{ matrix.script }}
