name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - .github/**
      - src/**
      - test/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/**
      - src/**
      - test/**

jobs:
  composer-script:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        script: ['unit-test', 'mutation-test', 'static-analysis']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - run: composer validate --strict
      - uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - run: composer install --prefer-dist --no-progress --no-interaction --no-suggest --no-scripts --no-ansi
      - run: composer run-script ${{ matrix.script }}
